strictness: veryhigh
doc-warnings: true
member-warnings: false
test-warnings: false

ignore-patterns:
  - (^|/)\..+
  - .*\.html
  - docs/.*
  - tmp.py
  - setup.py

pylint:
  disable:
    - bad-continuation
    - broad-except
    - import-error
    - import-self
    - protected-access
    - logging-format-interpolation
    - missing-docstring
    - no-self-use
    - unused-argument
    - wrong-import-order

  options:
    max-args: 20
    max-locals: 100
    max-returns: 6
    max-branches: 50
    max-statements: 180
    max-parents: 10
    max-attributes: 10
    min-public-methods: 0
    max-public-methods: 20
    max-module-lines: 2000
    max-line-length: 100

mccabe:
  options:
    max-complexity: 30

pycodestyle:
  disable:
    - N802
    - N807
    - N818
    - W503
    - W605
  options:
    max-line-length: 100
    single-line-if-stmt: n

vulture:
  run: false

pyroma:
  run: false

bandit:
  run: true

pydocstyle:
  disable:
    - D000
    - D100
    - D104
    - D107
    - D200
    - D202
    - D203
    - D205
    - D212
    - D204
    - D300
    - D400
    - D401
    - D404
    - D403
    - D415

pyflakes:
  disable:
    - F401
    - F403
    - F999
